BlogMvc/Controllers/AdminMakaleController.cs
using BlogMvc.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;
namespace BlogMvc.Controllers
{
    public class AdminMakaleController : Controller
    {
        Context db = new Context();
        //
        // GET: /AdminMakale/
        public ActionResult Index()
        {
         
            var makales = db.Makaleler.ToList();
            return View(makales);
        }

        //
        // GET: /AdminMakale/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /AdminMakale/Create
        public ActionResult Create()
        {
            ViewBag.KategoriID = new SelectList(db.Kategoriler, "KategoriID", "KategoriAdı");
            return View();
        }

        //
        // POST: /AdminMakale/Create
        [HttpPost]
        public ActionResult Create(Makale makale,string etiketler,HttpPostedFileBase Foto)
        {
            if (ModelState.IsValid)
            {
                if (Foto != null)
                {
                    WebImage img = new WebImage(Foto.InputStream);
                    FileInfo fotoinfo = new FileInfo(Foto.FileName);

                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(800, 350);
                    makale.Foto = "/Uploads/MakaleFoto/" + newfoto;﻿
                    img.Save("~/Uploads/MakaleFoto/" + newfoto);
                   


                }
                if (etiketler != null)
                {
                    string[] etiketdizi = etiketler.Split(',');
                    foreach (var i in etiketdizi)
                    {
                        var yenietiket = new Etiket { EtiketAdı = i };
                        db.Etiketler.Add(yenietiket);
                      
                    }
                }
                makale.UyeID = Convert.ToInt32(Session["uyeid"]);
                makale.Okunma = 1;
                db.Makaleler.Add(makale);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(makale);
        }

        //
        // GET: /AdminMakale/Edit/5
        public ActionResult Edit(int id)
        {
            var makale = db.Makaleler.Where(m => m.MakaleID == id).SingleOrDefault();
            if (makale == null)
            {
                return HttpNotFound();
            }
            ViewBag.KategoriID = new SelectList(db.Kategoriler, "KategoriID", "KategoriAdı", makale.KategoriID);
            return View(makale);
        }

        //
        // POST: /AdminMakale/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, HttpPostedFileBase Foto, Makale makale)
        {
            try
            {
                var makales = db.Makaleler.Where(m => m.MakaleID == id).SingleOrDefault();
                if (Foto != null)
                {
                    if (System.IO.File.Exists(Server.MapPath(makales.Foto)))
                    {
                        System.IO.File.Delete(Server.MapPath(makales.Foto));
                    }
                    WebImage img = new WebImage(Foto.InputStream);
                    FileInfo fotoinfo = new FileInfo(Foto.FileName);

                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(800, 350);
                    img.Save("~/Uploads/MakaleFoto/" + newfoto);
                    makales.Foto = "/Uploads/MakaleFoto/" + newfoto;
                    makales.Baslik = makale.Baslik;
                    makales.Icerik = makale.Icerik;
                    makales.KategoriID = makale.KategoriID;

                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View();
            }
            catch
            {
                ViewBag.KategoriID = new SelectList(db.Kategoriler, "KategoriID", "KategoriAdı", makale.KategoriID);
                return View(makale);
            }
        }

        //
        // GET: /AdminMakale/Delete/5
        public ActionResult Delete(int id)
        {
            var makale = db.Makaleler.Where(m => m.MakaleID == id).SingleOrDefault();
            if (makale == null)
            {
                return HttpNotFound();
            }
            return View(makale);
        }

        //
        // POST: /AdminMakale/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var makales = db.Makaleler.Where(m => m.MakaleID == id).SingleOrDefault();
                if (makales == null)
                {
                    return HttpNotFound();
                }
                if (System.IO.File.Exists(Server.MapPath(makales.Foto)))
                {
                    System.IO.File.Delete(Server.MapPath(makales.Foto));
                }
                foreach (var i in makales.Yorumlar.ToList())
                {
                    db.Yorumlar.Remove(i);
                }
               
                db.Makaleler.Remove(makales);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

BlogMvc/Views/AdminMakale/Create.cshtml
@model BlogMvc.Models.Makale

@{

    Layout = "~/Views/Shared/_LayoutPageAdmin.cshtml";
}


@using (Html.BeginForm("Create", "AdminMakale", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Makale</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.KategoriID, "KategoriID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KategoriID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KategoriID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Baslik, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Icerik, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="foto" id="Foto" accept=".png,.jpg,.gif,.JPEG,.jpeg" class="form-control" />
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
            </div>
        </div>
      
        <div class="form-group">
            @Html.Label("Etiketler", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("Etiketler")
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BlogMvc/Views/AdminMakale/Delete.cshtml
@model BlogMvc.Models.Makale

@{
  
    Layout = "~/Views/Shared/_LayoutPageAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Silmeyi onaylıyormusunuz?</h3>
<div>
    <h4>Makale</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Kategori.KategoriAdı)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategori.KategoriAdı)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Uye.KullanıcıAdı)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Uye.KullanıcıAdı)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Baslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Baslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Icerik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Icerik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Foto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tarih)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Okunma)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Okunma)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BlogMvc/Views/AdminMakale/Edit.cshtml
@model BlogMvc.Models.Makale

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutPageAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "AdminMakale", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Makale</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.MakaleID)

        <div class="form-group">
            @Html.LabelFor(model => model.Baslik, new { @class = "control-label col-md-2" })
           
             <div class="col-md-10">
                @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Icerik, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Icerik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Icerik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="foto" id="Foto" accept=".png,.jpg,.gif,.JPEG,.jpeg" class="form-control" />
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tarih, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
            </div>
        </div>

 

      
        <div class="form-group">
            @Html.LabelFor(model => model.KategoriID, "KategoriID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KategoriID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KategoriID, "", new { @class = "text-danger" })
            </div>
        </div>

    

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BlogMvc/Views/AdminMakale/Index.cshtml
@model IEnumerable<BlogMvc.Models.Makale>

@{
  
    Layout = "~/Views/Shared/_LayoutPageAdmin.cshtml";
}

<h2>Makaleler</h2>

<p>
    @Html.ActionLink("Yeni Makale", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Kategori.KategoriAdı)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Uye.KullanıcıAdı)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Baslik)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Icerik)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Foto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tarih)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Okunma)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Kategori.KategoriAdı)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Uye.KullanıcıAdı)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Baslik)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Icerik)
        </td>
        <td>
           <img width="75" src="@item.Foto" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tarih)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Okunma)
        </td>
        <td>
            @Html.ActionLink("Düzenle", "Edit", new { id=item.MakaleID }) |
         
            @Html.ActionLink("Sil", "Delete", new { id=item.MakaleID })
        </td>
    </tr>
}

</table>