BlogMvc/Controllers/AdminUyeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlogMvc.Models;

namespace BlogMvc.Controllers
{
    public class AdminUyeController : Controller
    {
        private Context db = new Context();

        // GET: /AdminUye/
        public ActionResult Index()
        {
            var uyeler = db.Uyeler.Include(u => u.Yetki);
            return View(uyeler.OrderByDescending(u=>u.UyeID).ToList());
        }

        // GET: /AdminUye/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uye uye = db.Uyeler.Find(id);
            if (uye == null)
            {
                return HttpNotFound();
            }
            return View(uye);
        }

        // GET: /AdminUye/Create
        public ActionResult Create()
        {
            ViewBag.YetkiID = new SelectList(db.Yetkiler, "YetkiID", "YetkiAdı");
            return View();
        }

        // POST: /AdminUye/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="UyeID,KullanıcıAdı,Email,Sifre,AdSoyad,YetkiID")] Uye uye)
        {
            if (ModelState.IsValid)
            {
                db.Uyeler.Add(uye);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.YetkiID = new SelectList(db.Yetkiler, "YetkiID", "YetkiAdı", uye.YetkiID);
            return View(uye);
        }

        // GET: /AdminUye/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uye uye = db.Uyeler.Find(id);
            if (uye == null)
            {
                return HttpNotFound();
            }
            ViewBag.YetkiID = new SelectList(db.Yetkiler, "YetkiID", "YetkiAdı", uye.YetkiID);
            return View(uye);
        }

        // POST: /AdminUye/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="UyeID,KullanıcıAdı,Email,Sifre,AdSoyad,YetkiID")] Uye uye)
        {
            if (ModelState.IsValid)
            {
                db.Entry(uye).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.YetkiID = new SelectList(db.Yetkiler, "YetkiID", "YetkiAdı", uye.YetkiID);
            return View(uye);
        }

        // GET: /AdminUye/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uye uye = db.Uyeler.Find(id);
            if (uye == null)
            {
                return HttpNotFound();
            }
            return View(uye);
        }

        // POST: /AdminUye/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Uye uye = db.Uyeler.Find(id);
            db.Uyeler.Remove(uye);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BlogMvc/Views/AdminUye/Create.cshtml
@model BlogMvc.Models.Uye

@{
   
    Layout = "~/Views/Shared/_LayoutPageAdmin.cshtml";
}




@using (Html.BeginForm("Create", "AdminUye", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Uye</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.KullanıcıAdı, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KullanıcıAdı, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KullanıcıAdı, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email,"", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sifre, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sifre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sifre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdSoyad, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdSoyad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdSoyad, "", new { @class = "text-danger" })
            </div>
        </div>

      

        <div class="form-group">
            @Html.LabelFor(model => model.YetkiID, "YetkiID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("YetkiID", null, htmlAttributes: new { @class = "form-control" })
                @*@Html.DropDownList("YetkiID", String.Empty)*@
                @Html.ValidationMessageFor(model => model.YetkiID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>

BlogMvc/Views/AdminUye/Delete.cshtml
@model BlogMvc.Models.Uye

@{
  
    Layout = "~/Views/Shared/_LayoutPageAdmin.cshtml";
}



<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Uye</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Yetki.YetkiAdı)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Yetki.YetkiAdı)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KullanıcıAdı)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KullanıcıAdı)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sifre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sifre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdSoyad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdSoyad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Foto)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" /> |
            @Html.ActionLink("Geri Dön", "Index")
        </div>
    }
</div>

BlogMvc/Views/AdminUye/Details.cshtml
@model BlogMvc.Models.Uye

@{
 
    Layout = "~/Views/Shared/_LayoutPageAdmin.cshtml";
}



<div>
    <h4>Uye</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Yetki.YetkiAdı)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Yetki.YetkiAdı)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KullanıcıAdı)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KullanıcıAdı)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sifre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sifre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdSoyad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdSoyad)
        </dd>

        <dt>
           <img src="@Model.Foto" width="75" class="img-circle" />
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Foto)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UyeID }) |
    @Html.ActionLink("Geri Dön", "Index")
</p>

BlogMvc/Views/AdminUye/Edit.cshtml
@model BlogMvc.Models.Uye

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutPageAdmin.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Uye</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.UyeID)

        <div class="form-group">
            @Html.LabelFor(model => model.KullanıcıAdı, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KullanıcıAdı, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KullanıcıAdı, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sifre, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sifre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sifre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdSoyad, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdSoyad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdSoyad, "", new { @class = "text-danger" })
            </div>
        </div>

      

        @*<div class="form-group">
            @Html.LabelFor(model => model.YetkiID, "YetkiID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("YetkiID", String.Empty)
                @Html.ValidationMessageFor(model => model.YetkiID)
            </div>
        </div>*@
        <div class="form-group">
            @Html.LabelFor(model => model.YetkiID, "YetkiID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("YetkiID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.YetkiID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>

BlogMvc/Views/AdminUye/Index.cshtml
@model IEnumerable<BlogMvc.Models.Uye>

@{
    Layout = "~/Views/Shared/_LayoutPageAdmin.cshtml";
}



<p>
    @Html.ActionLink("Yeni Uye", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Yetki.YetkiAdı)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KullanıcıAdı)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sifre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AdSoyad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Foto)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Yetki.YetkiAdı)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.KullanıcıAdı)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sifre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AdSoyad)
        </td>
        <td>
           <img src="@item.Foto" class="img-circle" width="50" />
        </td>
        <td>
            @Html.ActionLink("Düzenle", "Edit", new { id=item.UyeID }) |
            @Html.ActionLink("Detay", "Details", new { id=item.UyeID }) |
            @Html.ActionLink("Sil", "Delete", new { id=item.UyeID })
        </td>
    </tr>
}

</table>